- locales/ru.yml
Hi.
I have found some spelling mistakes in Russian locale.
This PR is going to fix it.
> update russian locale

- locales/pt-BR.yml
#28 Improved pt_BR translation.
It's a kind of difficult to use the most appropriate words without a context, but I hope it helps you!
> Improved pt_BR translation.

- locales/fi-FI.yml
Initial Finnish translation for #28.
> Add Finnish translation

- locales/es-MX.yml
Just fixed grammar and added some missing items, also replaced most of items to match `en.yml` model. Fixes part of #28 .
> Fix locale for Spanish (Mexico)

- locales/ro.yml
Add new language. https://github.com/starchow/rails_admin-i18n/issues/28
> Add romanian translation

- locales/ru.yml
> Fix ru translations

- locales/be.yml
> Added Belarusian translation

- locales/zh-TW.yml
There are some simplified Chinese (zh-CN) characters.
(#28)
> Fixed zh-TW translation (#28)

- locales/pl.yml
> Add last_created to Polish translation

- locales/pl.yml
This mostly fixes spaces and sentence order. It still sounds stiff but it comprehensible.
> Fix Polish locale

- locales/pt.yml
for Angola, Cabo Verde, Guiné-Bissau, Moçambique, Portugal, São Tomé e Príncipe and Timor Leste
> Add pt translation

- locales/ja.yml
@starchow 
I've added `ja.admin.table_headers.last_created`.
> add ja.admin.table_headers.last_created

- locales/nb-NO.yml
Added Norwegian Bokmål translation file
> Norwegian translation (nb-NO)

- locales/el.yml
> Add greek translation

- locales/fil.yml
Filipino translations. Please accept as part of Hacktoberfest. Thank you
> Filipino translations

- locales/mk.yml
Hello there!
Added macedonian translations to help out with #28
Happy hacktoberfest! Thanks for opting in your project!
Cheers!
> Macedonian translations.

- locales/ru.yml
update ru locale with the next strings:
```
$ rake i18n-spec:completeness locales/en.yml locales/ru.yml 
- *COMPLETE* 
```
> Complete Russian translation

- locales/de.yml
Added missing translation for key _de.admin.actions.index.no_records_
> Added missing translation for key de.admin.actions.index.no_records

- locales/en.yml
- locales/sk.yml
The pull request adds missing keys from latest English locale from rails_admin project and adds missing Slovak translations.
> Add missing keys from rails_admin 3

- locales/ca.yml
- rails_admin-i18n.gemspec
This branch contains the catalan translations for rails_admin. Feel free to make or ask me any changes :)
> Add catalan locale

- locales/nl.yml
Brings Dutch translations in-line with the English.
> Update NL translations
